[package]
name = "bls-signatures"
description = ""
version = "1.2.5"
edition = "2021"

[features]
legacy = []
bip32 = []
default = [ "legacy", "bip32" ]

[dependencies]
bls-dash-sys = { path = "../bls-dash-sys" }
