[package]
name = "bls-signatures-autocxx"
version = "1.2.4"
build = "build.rs"
edition = "2018"

[dependencies]
autocxx = "0.22"
cxx = "1.0"

[build-dependencies]
autocxx-build = "0.22"
miette = { version="4.7", features=["fancy"] }